# Generated by Django 2.1.13 on 2019-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191019_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelname',
            old_name='tiile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='modelname',
            name='description',
            field=models.CharField(default='在这里写作品的简介', max_length=100),
        ),
    ]
